image: ubuntu:18.04

before_script:
  - apt-get update && apt-get -y install make curl gnupg2

stages:
  - web-frontend-lint
  - web-frontend-test

web-frontend-eslint:
  stage: web-frontend-lint
  script:
    - make install-web-frontend-dependencies
    - (cd web-frontend && yarn run eslint)

web-frontend-stylelint:
  stage: web-frontend-lint
  script:
    - make install-web-frontend-dependencies
    - (cd web-frontend && yarn run stylelint)

web-frontend-test:
  stage: web-frontend-test
  script:
    - make install-web-frontend-dependencies
    - (cd web-frontend && yarn run test)
